from . import start_hr
from . import a_main_menu
from . import admin_hr
from . import quran_duolar
from . import quranmuqriy_hr
from . import ramazon1443_hr
from . import taroveh1443_hr
from . import qurantanishuv_hr
from . import mushafistilohlari_hr
from . import qasam_hr
from . import iqro_hr
from . import qurantartil_hr
from . import quranverse_hr
from . import quranversenext_hr
from . import qurantalimi_hr
from . import hamnafas_hr
from . import tahoratvanamoz_hr
from . import shamoil_hr
from . import arbain_hr
from . import mavlid_hr
from . import qadamjolar_hr
from . import ilmiysuhbatlar_hr
from . import misrsafari_hr
from . import hamsafar_hr
from . import haj_hr
from . import navoiyanglash_hr
from . import zikrlar_hr
from . import juma_suhbatlari_handler
from . import muqriyverse
from . import toshshahar_suhbatlar_handler
from . import toplam_handlers
from . import quran_screens
from . import taroveh1444
