# Generated by Django 3.2.8 on 2024-06-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuranVerseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sura_number', models.IntegerField(null=True, verbose_name='Sura tartib raqami')),
                ('sura_name', models.CharField(blank=True, max_length=50, verbose_name='Sura nomi')),
                ('audio_url', models.CharField(blank=True, max_length=150, verbose_name='Sura audio url manzili')),
                ('photo_url', models.CharField(blank=True, max_length=150, verbose_name='Sura rasmi url manzili')),
                ('zip_id', models.CharField(blank=True, max_length=150, verbose_name='ZIP ID')),
                ('total_verses', models.IntegerField(max_length=3, null=True, verbose_name='Umumiy oyatlar soni')),
            ],
            options={
                'verbose_name': 'QuranVerseByVerse',
                'verbose_name_plural': 'QuranVerseByVerse',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Telegram username')),
                ('telegram_id', models.BigIntegerField(default=1, unique=True, verbose_name='Telegram ID')),
            ],
            options={
                'verbose_name': 'Foydalanuvchilar',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
    ]
