# Generated by Django 3.2.8 on 2024-06-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quranversemodel',
            name='sura_number',
            field=models.IntegerField(max_length=3, null=True, verbose_name='Sura tartib raqami'),
        ),
    ]
