# Generated by Django 5.0.6 on 2024-06-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_alter_quranversemodel_sura_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quranversemodel',
            name='sura_number',
            field=models.IntegerField(null=True, verbose_name='Sura tartib raqami'),
        ),
        migrations.AlterField(
            model_name='quranversemodel',
            name='total_verses',
            field=models.IntegerField(null=True, verbose_name='Umumiy oyatlar soni'),
        ),
    ]
