from . import start_dk
from . import quranmuqriy_dk
from . import audio_video_dk
from . import ramazon1443_dk
from . import taroveh1443_dk
from . import mushafistilohlari_dk
from . import qasam_dk
from . import iqro_dk
from . import qurantartil_dk
from . import qversedk
from . import quran_talimi
from . import hamnafas_dk
from . import tahoratvanamoz_dk
from . import shamoil_dk
from . import arbain_dk
from . import mavlid_dk
from . import qadamjolar_dk
from . import ilmiysuhbatlar_dk
from . import misrsafari_dk
from . import hamsafar_dk
from . import navoiyanglash_dk
from . import zikrlar_dk
from . import adminkeys
from . import savol_dk
from . import juma_mav_dk
from . import muqriyverse_buttons
from . import users_custom_buttons